### PR TITLE
Improves the CI/CD experience

### PR DESCRIPTION
**Pull request by SSmale**
- allow only deploy to be run manually
- check if the patch has already happened
- if there is a patch, use the new code to deploy

### CODE REVIEW

**Comment by jesp209i** [comment]
Hi @SSmale,
This looks very interesting. 
The plan is that we will test this out (finger crossed in the upcoming days) and then if everything checks out and tests well, we'll try to apply this approach to the Azure samples also

**Comment by SSmale** [comment]
Thanks @jesp209i I think there are some more tweaks needed but I ran out of my free trial to finish the fixes.

**Comment by jesp209i** [comment]
This still looks very interesting - unfortunately I am yet to test it out. I just wanted to say it has not been forgotten :)

**Comment by jesp209i** [comment]
@SSmale thanks for the contribution - this is a really nice tweak
I only made one correction to how the pipeline stores the updated sha, besides that this seem to work pretty well.
I just want to do a little more work before adding this to main branch

**Pull request merged**
